SplashText = [
    "E",
    "a.",
    "ඞ",
    "text",
    "Async!",
    "*ping*",
    "🤸 🦽🏌️",
    "random text!",
    "Wooo, memes!",
    "open source!",
    "goofy aah bot",
    "Python Edition",
    "Work of Shibzel!",
    "I'm in your walls.",
    "computer compatible!",
    "69420 lines of code!",
    "69 haha funni number",
    "i'm fucking retarded", 
    "boTs havE riGhts ToO",
    ".　　 。　 ඞ 。 . 　　•",
    "i love microplastics!",
    "i got a gun in my rari",
    "Water proof! (probably)",
    "shibe going to space :O",
    "random splash text, go !",
    "thanks for using shibbot!",
    "really cool ascii art huh?",
    "I know your exact location.",
    "created in 2021 (who cares ?)",
    "Why are you even reading this",
    "https://github.com/Shibzel/Shibbot",
    "Around the World, Around the World 🎶",
    "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "https://www.youtube.com/watch?v=JuEa6Hum0b4",
    "https://www.youtube.com/watch?v=ZE4yIP2V2uQ",
    "microwaves be like: hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm *ding*",
    "STOP POSTING ABOUT AMONG US, I'M TIRED OF SEEING IT! My friends on TikTok send me memes, on Discord it's fucking memes, i was in a server, right? and ALL of the channels are just Among Us stuff. I-I showed my Champion underwear to my girlfriend, and the logo i flipped it and i said \"Hey babe, when the underwear sus HAHA ding ding ding ding ding ding ding *takes breath* ding ding ding\" I FUCKING LOOKED AT A TRASH CAN, I SAID \"THAT'S A BIT SUSSY\", I LOOKED AT MY PENIS, I THINK OF THE ASTRONAUT'S HELMET, AND I GO \"PENIS, more like peenSUS\" *takes breath* AAAAAAAAAAAAAAA", 
]